/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.muumilaakso.ui;

import com.muumilaakso.management.Reference;
import java.util.ArrayList;

/**
 *
 * @author jusalo
 */
public class MiniTuhoUI extends javax.swing.JFrame {

    Reference ref;
    ArrayList<String> auth;

    /**
     * Creates new form MiniTuhoUI
     */
    public MiniTuhoUI() {
        initComponents();
        auth = new ArrayList<String>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBtn = new javax.swing.JButton();
        editTab = new javax.swing.JTabbedPane();
        addPnl = new javax.swing.JPanel();
        refType = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        refAuthor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        refTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        refYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        refBooktitle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        refPublisher = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        refPages = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        refAddress = new javax.swing.JTextField();
        addAuthBtn = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("teX");

        closeBtn.setText("Sulje");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        addPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Uusi viite"));

        refType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Tyyppi");

        addBtn.setText("Lisää");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Tekijä");

        refAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refAuthorActionPerformed(evt);
            }
        });
        refAuthor.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                refAuthorInputMethodTextChanged(evt);
            }
        });

        jLabel3.setText("Nimi");

        refTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refTitleActionPerformed(evt);
            }
        });

        jLabel4.setText("Vuosi");

        refYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refYearActionPerformed(evt);
            }
        });

        jLabel5.setText("Otsikko");

        refBooktitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refBooktitleActionPerformed(evt);
            }
        });

        jLabel6.setText("Julkaisija");

        refPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refPublisherActionPerformed(evt);
            }
        });

        jLabel7.setText("Sivut");

        refPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refPagesActionPerformed(evt);
            }
        });

        jLabel8.setText("Osoite");

        refAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refAddressActionPerformed(evt);
            }
        });

        addAuthBtn.setText("Uusi");
        addAuthBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPnlLayout = new javax.swing.GroupLayout(addPnl);
        addPnl.setLayout(addPnlLayout);
        addPnlLayout.setHorizontalGroup(
            addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(46, 46, 46)
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(refType)
                    .addGroup(addPnlLayout.createSequentialGroup()
                        .addComponent(refAuthor)
                        .addGap(63, 63, 63)
                        .addComponent(addAuthBtn))
                    .addComponent(refTitle)
                    .addComponent(refYear)
                    .addComponent(refBooktitle)
                    .addComponent(refPublisher)
                    .addComponent(refPages)
                    .addComponent(refAddress))
                .addContainerGap())
            .addGroup(addPnlLayout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(addBtn)
                .addGap(12, 12, 12))
        );
        addPnlLayout.setVerticalGroup(
            addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(refAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAuthBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(refTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(refYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(refBooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(refPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(refPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(refAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn)
                .addContainerGap())
        );

        editTab.addTab("Lisää", addPnl);
        editTab.addTab("Muokkaa", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBtn)
                .addContainerGap())
            .addComponent(editTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(editTab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String type = refType.getText();
        auth.add(refAuthor.getText());
        String title = refTitle.getText();
        int year = Integer.parseInt(refYear.getText());
        String booktitle = refBooktitle.getText();
        String publisher = refPublisher.getText();
        String pages = refPages.getText();
        String address = refAddress.getText();

        ref = new Reference(type, null, title, year, booktitle, publisher, pages, address);
    }//GEN-LAST:event_addBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void refTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refTypeActionPerformed

    private void refAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refAuthorActionPerformed

    private void refTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refTitleActionPerformed

    private void refYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refYearActionPerformed

    private void refBooktitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refBooktitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refBooktitleActionPerformed

    private void refPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refPublisherActionPerformed

    private void refPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refPagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refPagesActionPerformed

    private void refAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refAddressActionPerformed

    private void addAuthBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthBtnActionPerformed
        // TODO add your handling code here:
        String author = refAuthor.getText();
        auth.add(author);
        refAuthor.setText("");
    }//GEN-LAST:event_addAuthBtnActionPerformed

    private void refAuthorInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_refAuthorInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_refAuthorInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniTuhoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniTuhoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniTuhoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniTuhoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MiniTuhoUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAuthBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addPnl;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTabbedPane editTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField refAddress;
    private javax.swing.JTextField refAuthor;
    private javax.swing.JTextField refBooktitle;
    private javax.swing.JTextField refPages;
    private javax.swing.JTextField refPublisher;
    private javax.swing.JTextField refTitle;
    private javax.swing.JTextField refType;
    private javax.swing.JTextField refYear;
    // End of variables declaration//GEN-END:variables
}
